#Swiss Spending Simulator parameters
seed=time
nbSteps=365
multiplier=1
nbClients=1000
nbFraudsters=0
nbMerchants=500
nbBanks=5
fraudProbability=0.0
transferLimit=1000000
transactionsTypes=./paramFiles/swissTransactionsTypes.csv
aggregatedTransactions=./paramFiles/swissAggregatedTransactions.csv
clientsProfiles=./paramFiles/swissClientsProfiles.csv
initialBalancesDistribution=./paramFiles/swissInitialBalancesDistribution.csv
overdraftLimits=./paramFiles/swissOverdraftLimits.csv
maxOccurrencesPerClient=./paramFiles/swissMaxOccurrencesPerClient.csv
typologiesFolder=./paramFiles/typologies/
outputPath=./outputs/
saveToDB=0
dbUrl=jdbc:mysql://localhost:3306/swissspending
dbUser=none
dbPassword=none
